{% set version = "4.9.2" %}

package:
  name: lxml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: 2455cfaeb7ac70338b3257f41e21f0724f4b5b0c0e7702da67ee6c3640835b67
  patches:
    - fix-initialization.patch

build:
  number: 1
  script:
    - set "PKG_CONFIG_PATH=%LIBRARY_LIB%\pkgconfig;%LIBRARY_PREFIX%\share\pkgconfig"  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - pkg-config
  host:
    - libxml2
    - python
    - pip
    - cython
    - libxslt
    - zlib
  run:
    - python

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://lxml.de/
  license: BSD-3-Clause and GPL-2.0-only and ZPL-2.0 and LicenseRef-ElementTree
  license_file: LICENSES.txt
  summary: Pythonic binding for the C libraries libxml2 and libxslt.
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: http://lxml.de/index.html#documentation
  dev_url: https://github.com/lxml/lxml
  doc_source_url: https://github.com/lxml/lxml/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
    - zklaus
