{% set version = "4.9.1" %}

package:
  name: lxml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: fe749b052bb7233fe5d072fcb549221a8cb1a16725c47c37e42b0b9cb3ff2c3f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - pkg-config
  host:
    # exclusions due to https://bugs.launchpad.net/lxml/+bug/1928795
    - libxml2 !=2.9.11, !=2.9.12
    - python
    - pip
    - cython
    - libxslt
    - zlib
  run:
    - python
    - libxslt
    - libxml2 !=2.9.11, !=2.9.12

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://lxml.de/
  license: BSD-3-Clause and GPL-2.0-only and ZPL-2.0 and LicenseRef-ElementTree
  license_file: LICENSES.txt
  summary: Pythonic binding for the C libraries libxml2 and libxslt.
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: http://lxml.de/index.html#documentation
  dev_url: https://github.com/lxml/lxml
  doc_source_url: https://github.com/lxml/lxml/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
